[setting.pythEurFeedId]
defaultValue = "0xa995d00bb36a63cef7fd2c287dc105fc8f3d93779f062f09551b0af3e81ec30b"

[setting.eurPerpsMarketId]
defaultValue = "8100"

[setting.perpsEurSkewScale]
defaultValue = "<%= String(118_000_000) %>"
# defaultValue = "<%= String(416_666_666.7) %>"

[setting.perpsEurMaxFundingVelocity]
defaultValue = "0"

[setting.perpsEurLimitOrderMakerFeeRatio]
defaultValue = "0.0001"

[setting.perpsEurLimitOrderTakerFeeRatio]
defaultValue = "0.0002"

[setting.perpsEurMakerFeeRatio]
defaultValue = "0.0004"

[setting.perpsEurTakerFeeRatio]
defaultValue = "0.0006"

[setting.perpsEurMaxMarketSize]
defaultValue = "<%= String(0) %>"

[setting.perpsEurMaxMarketValue]
defaultValue = "<%= String(0) %>"

[setting.perpsEurInitialMarginRatio]
defaultValue = "0.133"

[setting.perpsEurMinimumInitialMarginRatio]
defaultValue = "0.005"

[setting.perpsEurMaintenanceMarginScalar]
defaultValue = "0.28"

[setting.perpsEurFlagRewardRatioD18]
defaultValue = "0.0003"

[setting.perpsEurMaxLiquidationLimitAccumulationMultiplier]
defaultValue = "1.5"

[setting.perpsEurMaxSecondsInLiquidationWindow]
defaultValue = "30"

[setting.perpsEurMinimumPositionMargin]
defaultValue = "25"

[setting.perpsEurLockedOiRatio]
defaultValue = "0.5"

[setting.perpsEurSynthMaxCollateralAmount]
defaultValue = "<%= MaxUint256 %>"

[setting.perpsEurMaxLiquidationPd]
defaultValue = "0.0005"

[setting.perpsEurRolloverFee]
defaultValue = "1585489600"

[setting.perpsEurEndorsedLiquidator]
defaultValue = "0x38D4200767628f4197C5d5FdDA24927C28dDadeF"
