[invoke.setPerpsKeeperSettlementRewardOverride]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setSettlementRewardOverride"
args = ["4232011895", true]
depends = ["provision.perpsFactory"]