[setting.perpsAeroFeedId]
defaultValue = "0x9db37f4d5654aad3e37e2e14ffd8d53265fb3026d1d8f91146539eebaa2ef45f"

[setting.perpsAeroMarketId]
defaultValue = "5300"

[setting.perpsAeroSkewScale]
defaultValue = "<%= String(6_000_000) %>"

[setting.perpsAeroMaxFundingVelocity]
defaultValue = "24"

[setting.perpsAeroMakerFeeRatio]
defaultValue = "0.0004"

[setting.perpsAeroTakerFeeRatio]
defaultValue = "0.0006"

[setting.perpsAeroLimitOrderMakerFeeRatio]
defaultValue = "0.0001"

[setting.perpsAeroLimitOrderTakerFeeRatio]
defaultValue = "0.0002"

[setting.perpsAeroMaxMarketSize]
defaultValue = "<%= String(0) %>"

[setting.perpsAeroMaxMarketValue]
defaultValue = "<%= String(0) %>"

[setting.perpsAeroInitialMarginRatio]
defaultValue = "0.3472222222222201"

[setting.perpsAeroMaintenanceMarginScalar]
defaultValue = "0.26"

[setting.perpsAeroMinimumInitialMarginRatio]
defaultValue = "0.05"

[setting.perpsAeroFlagRewardRatioD18]
defaultValue = "0.0003"

[setting.perpsAeroMaxLiquidationLimitAccumulationMultiplier]
defaultValue = "1.5"

[setting.perpsAeroMaxSecondsInLiquidationWindow]
defaultValue = "30"

[setting.perpsAeroMinimumPositionMargin]
defaultValue = "25"

[setting.perpsAeroLockedOiRatio]
defaultValue = "0.5"

[setting.perpsAeroSynthMaxCollateralAmount]
defaultValue = "<%= MaxUint256 %>"

[setting.perpsAeroMaxLiquidationPd]
defaultValue = "0.0005"

[setting.perpsAeroEndorsedLiquidator]
defaultValue = "0x38D4200767628f4197C5d5FdDA24927C28dDadeF"

[setting.commitmentPriceDelay]
defaultValue = "2"

[setting.bigCapSettlementDelay]
defaultValue = "2"
