[setting.pythEthFeedId]
defaultValue = "0xff61491a931112ddf1bd8147cd1b641375f79f5825126d665480874634fd0ace"

[setting.pythEthLazerFeedId]
defaultValue = "2"

[setting.ethPerpsMarketId]
defaultValue = "100"

[setting.perpsEthSkewScale]
defaultValue = "<%= String(50_000) %>"

[setting.perpsEthMaxFundingVelocity]
defaultValue = "9"

[setting.perpsEthLimitOrderMakerFeeRatio]
defaultValue = "0.0000"

[setting.perpsEthLimitOrderTakerFeeRatio]
defaultValue = "0.0000"

[setting.perpsEthMakerFeeRatio]
defaultValue = "0"

[setting.perpsEthTakerFeeRatio]
defaultValue = "0"

[setting.perpsEthMaxMarketSize]
defaultValue = "<%= String(1_288_000) %>"

[setting.perpsEthMaxMarketValue]
defaultValue = "<%= String(5_000_000) %>"

[setting.perpsEthInitialMarginRatio]
defaultValue = "1.16"

[setting.perpsEthMinimumInitialMarginRatio]
defaultValue = "0.02"

[setting.perpsEthMaintenanceMarginScalar]
defaultValue = "0.23"

[setting.perpsEthFlagRewardRatioD18]
defaultValue = "0.0003"

[setting.perpsEthMaxLiquidationLimitAccumulationMultiplier]
defaultValue = "1.5"

[setting.perpsEthMaxSecondsInLiquidationWindow]
defaultValue = "30"

[setting.perpsEthMinimumPositionMargin]
defaultValue = "25"

[setting.perpsEthLockedOiRatio]
defaultValue = "0.5"

[setting.perpsEthSynthMaxCollateralAmount]
defaultValue = "<%= MaxUint256 %>"

[setting.perpsEthMaxLiquidationPd]
defaultValue = "0.0005"

[setting.perpsEthRolloverFee]
defaultValue = "1585489600"

[setting.perpsEthEndorsedLiquidator]
defaultValue = "0x38D4200767628f4197C5d5FdDA24927C28dDadeF"
