[setting.pythJpyFeedId]
defaultValue = "0xef2c98c804ba503c6a707e38be4dfbb16683775f195b091252bf24693042fd52"

[setting.jpyPerpsMarketId]
defaultValue = "8200"

[setting.perpsJpySkewScale]
defaultValue = "<%= String(3_125_000) %>"

[setting.perpsJpyMaxFundingVelocity]
defaultValue = "0"

[setting.perpsJpyLimitOrderMakerFeeRatio]
defaultValue = "0.0001"

[setting.perpsJpyLimitOrderTakerFeeRatio]
defaultValue = "0.0002"

[setting.perpsJpyMakerFeeRatio]
defaultValue = "0.0004"

[setting.perpsJpyTakerFeeRatio]
defaultValue = "0.0006"

[setting.perpsJpyMaxMarketSize]
defaultValue = "<%= String(0) %>"

[setting.perpsJpyMaxMarketValue]
defaultValue = "<%= String(0) %>"

[setting.perpsJpyInitialMarginRatio]
defaultValue = "0.02"

[setting.perpsJpyMinimumInitialMarginRatio]
defaultValue = "0.005"

[setting.perpsJpyMaintenanceMarginScalar]
defaultValue = "0.26"

[setting.perpsJpyFlagRewardRatioD18]
defaultValue = "0.0003"

[setting.perpsJpyMaxLiquidationLimitAccumulationMultiplier]
defaultValue = "1.5"

[setting.perpsJpyMaxSecondsInLiquidationWindow]
defaultValue = "30"

[setting.perpsJpyMinimumPositionMargin]
defaultValue = "25"

[setting.perpsJpyLockedOiRatio]
defaultValue = "0.5"

[setting.perpsJpySynthMaxCollateralAmount]
defaultValue = "<%= MaxUint256 %>"

[setting.perpsJpyMaxLiquidationPd]
defaultValue = "0.0005"

[setting.perpsJpyRolloverFee]
defaultValue = "1585489600"

[setting.perpsJpyEndorsedLiquidator]
defaultValue = "0x38D4200767628f4197C5d5FdDA24927C28dDadeF"
