[setting.fxUsd0MaxMarketCollateral]
defaultValue = "<%= parseEther(String(10_000_000)) %>"

[setting.fxUsd0SkewScale]
defaultValue = "<%= parseEther(String(0)) %>"

[setting.spotStrictStalenessTolerance]
defaultValue = "300"

[setting.pyth_feed_id_usd0]
defaultValue = "0xf9c96a45784d0ce4390825a43a313149da787e6a6c66076f3a3f83e92501baeb"

[setting.pyth_feed_url_usd0]
defaultValue = "https://hermes.pyth.network/v2/updates/price/latest?ids[]=<%= settings.pyth_feed_id_usd0 %>"

[setting.usd0_address]
defaultValue = "0xb9B44F3A8956977A6aB24Fb84fBbc84e97eFf0F9"

[invoke.createUsd0Synth]
target = ["spotFactory.SpotMarketProxy"]
fromCall.func = "owner"
func = "createSynth"
args = ["Polynomial USD0++", "fxUSD0++", "<%= settings.owner %>"]
extra.fx_usd0_market_id.event = "SynthRegistered"
extra.fx_usd0_market_id.arg = 0
extra.fx_usd0_token_address.event = "SynthRegistered"
extra.fx_usd0_token_address.arg = 1

[invoke.setSynthPriceUsd0]
target = ["spotFactory.SpotMarketProxy"]
fromCall.func = "getMarketOwner"
fromCall.args = ["<%= extras.fx_usd0_market_id %>"]
func = "updatePriceData"
args = [
    "<%= extras.fx_usd0_market_id %>",
    "<%= extras.usd0_staleness_oracle_id %>",
    "<%= extras.usd0_staleness_oracle_id %>",
    "<%= settings.spotStrictStalenessTolerance %>",
]

[invoke.setSynthMaxMarketCollateralUsd0]
target = ["system.CoreProxy"]
fromCall.func = "owner"
fromCall.args = []
func = "configureMaximumMarketCollateral"
args = [
    "<%= extras.fx_usd0_market_id %>",
    "<%= settings.usd0_address %>",
    "<%= settings.fxUsd0MaxMarketCollateral %>",
]

[invoke.setSkewScaleUsd0]
target = ["spotFactory.SpotMarketProxy"]
fromCall.func = "getMarketOwner"
fromCall.args = ["<%= extras.fx_usd0_market_id %>"]
func = "setMarketSkewScale"
args = ["<%= extras.fx_usd0_market_id %>", "<%= settings.fxUsd0SkewScale %>"]

[invoke.configureSynthWrapperUsd0]
target = ["spotFactory.SpotMarketProxy"]
fromCall.func = "getMarketOwner"
fromCall.args = ["<%= extras.fx_usd0_market_id %>"]
func = "setWrapper"
args = [
    "<%= extras.fx_usd0_market_id %>",
    "<%= settings.usd0_address %>",
    "<%= settings.fxUsd0MaxMarketCollateral %>",
]

# NOTE set disabled = true to addSettlementStrategy call before initial mainnet deployment
[invoke.SpotMarketProxy_addSettlementStrategy_usd0]
target = ["spotFactory.SpotMarketProxy"]
fromCall.func = "getMarketOwner"
fromCall.args = ["<%= extras.fx_usd0_market_id %>"]
func = "addSettlementStrategy"
args = [
    "<%= extras.fx_usd0_market_id %>",
    { strategyType = "1", settlementDelay = "0", settlementWindowDuration = "1", priceVerificationContract = "0x0000000000000000000000000000000000000000", feedId = "0x0000000000000000000000000000000000000000000000000000000000000000", url = "", settlementReward = 0, minimumUsdExchangeAmount = "0", maxRoundingLoss = "1", priceDeviationTolerance = "0", disabled = false },
]
extra.fx_usd0_settlement_strategy_id.event = "SettlementStrategyAdded"
extra.fx_usd0_settlement_strategy_id.arg = 1

[invoke.SpotMarketProxy_setSettlementStrategy_fxUSD0]
target = ["spotFactory.SpotMarketProxy"]
fromCall.func = "getMarketOwner"
fromCall.args = ["<%= extras.fx_usd0_market_id %>"]
func = "setSettlementStrategy"
args = [
    "<%= extras.fx_usd0_market_id %>",
    "<%= extras.fx_usd0_settlement_strategy_id %>",
    { strategyType = "1", settlementDelay = "<%= settings.big_cap_settlement_delay %>", settlementWindowDuration = "<%= settings.big_cap_settlement_window_duration %>", priceVerificationContract = "<%= imports.pyth_erc7412_wrapper.contracts.PythERC7412Wrapper.address %>", feedId = "<%= settings.pyth_feed_id_usd0 %>", url = "<%= settings.pyth_feed_url_usd0 %>", settlementReward = "<%= settings.settlement_reward %>", minimumUsdExchangeAmount = "<%= settings.settlement_minimum_usd_exchange_amount %>", maxRoundingLoss = "<%= settings.settlement_max_rounding_loss %>", priceDeviationTolerance = "<%= settings.price_deviation_tolerance %>", disabled = true },
]

[invoke.SpotMarketProxy_setAtomicFixedFee_fxUSD0]
target = ["spotFactory.SpotMarketProxy"]
fromCall.func = "getMarketOwner"
fromCall.args = ["<%= extras.fx_usd0_market_id %>"]
func = "setAtomicFixedFee"
args = ["<%= extras.fx_usd0_market_id %>", "<%= parseEther(String(0.001)) %>"]

[invoke.configure_fxusd0_collateral]
target = ["system.CoreProxy"]
fromCall.func = "owner"
func = "configureCollateral"  # "args" see below in the multiline block

[[invoke.configure_fxusd0_collateral.args]]
tokenAddress = "<%= extras.fx_usd0_token_address %>"
oracleNodeId = "<%= extras.usd0_staleness_oracle_id %>"
issuanceRatioD18 = "<%= MaxUint256 %>"
liquidationRatioD18 = "<%= parseEther('1.1') %>"
liquidationRewardD18 = "<%= parseEther('0.0001') %>"
minDelegationD18 = "<%= parseEther('100') %>"
depositingEnabled = true
