[setting.fxSusdeMaxMarketCollateral]
defaultValue = "<%= parseEther(String(2500)) %>"

[setting.fxSusdeSkewScale]
defaultValue = "<%= parseEther(String(350_000)) %>"

[setting.spotStrictStalenessTolerance]
defaultValue = "300"

[setting.pyth_feed_id_susde]
defaultValue = "0xca3ba9a619a4b3755c10ac7d5e760275aa95e9823d38a84fedd416856cdba37c"

[setting.pyth_feed_url_susde]
defaultValue = "https://hermes.pyth.network/v2/updates/price/latest?ids[]=<%= settings.pyth_feed_id_susde %>"

[setting.susde_address]
defaultValue = "0x2A06DEAc3E863c23DD6a89Eeacd80aBA9E08B77B"

[invoke.createSusdeSynth]
target = ["spotFactory.SpotMarketProxy"]
fromCall.func = "owner"
func = "createSynth"
args = ["Polynomial sUSDe", "fxSUSDe", "<%= settings.owner %>"]
extra.fx_susde_market_id.event = "SynthRegistered"
extra.fx_susde_market_id.arg = 0
extra.fx_susde_token_address.event = "SynthRegistered"
extra.fx_susde_token_address.arg = 1

[invoke.setSynthPriceSusde]
target = ["spotFactory.SpotMarketProxy"]
fromCall.func = "getMarketOwner"
fromCall.args = ["<%= extras.fx_susde_market_id %>"]
func = "updatePriceData"
args = [
    "<%= extras.fx_susde_market_id %>",
    "<%= extras.SUSDE_staleness_oracle_id %>",
    "<%= extras.SUSDE_staleness_oracle_id %>",
    "<%= settings.spotStrictStalenessTolerance %>",
]

[invoke.setSynthMaxMarketCollateralSusde]
target = ["system.CoreProxy"]
fromCall.func = "owner"
fromCall.args = []
func = "configureMaximumMarketCollateral"
args = [
    "<%= extras.fx_susde_market_id %>",
    "<%= settings.susde_address %>",
    "<%= settings.fxSusdeMaxMarketCollateral %>",
]

[invoke.setSkewScaleSusde]
target = ["spotFactory.SpotMarketProxy"]
fromCall.func = "getMarketOwner"
fromCall.args = ["<%= extras.fx_susde_market_id %>"]
func = "setMarketSkewScale"
args = ["<%= extras.fx_susde_market_id %>", "<%= settings.fxSusdeSkewScale %>"]

[invoke.configureSynthWrapperSusde]
target = ["spotFactory.SpotMarketProxy"]
fromCall.func = "getMarketOwner"
fromCall.args = ["<%= extras.fx_susde_market_id %>"]
func = "setWrapper"
args = [
    "<%= extras.fx_susde_market_id %>",
    "<%= settings.susde_address %>",
    "<%= settings.fxSusdeMaxMarketCollateral %>",
]

# NOTE set disabled = true to addSettlementStrategy call before initial mainnet deployment
[invoke.SpotMarketProxy_addSettlementStrategy_susde]
target = ["spotFactory.SpotMarketProxy"]
fromCall.func = "getMarketOwner"
fromCall.args = ["<%= extras.fx_susde_market_id %>"]
func = "addSettlementStrategy"
args = [
    "<%= extras.fx_susde_market_id %>",
    { strategyType = "1", settlementDelay = "0", settlementWindowDuration = "1", priceVerificationContract = "0x0000000000000000000000000000000000000000", feedId = "0x0000000000000000000000000000000000000000000000000000000000000000", url = "", settlementReward = 0, minimumUsdExchangeAmount = "0", maxRoundingLoss = "1", priceDeviationTolerance = "0", disabled = false },
]
extra.fx_susde_settlement_strategy_id.event = "SettlementStrategyAdded"
extra.fx_susde_settlement_strategy_id.arg = 1

[invoke.SpotMarketProxy_setSettlementStrategy_fxSUSDe]
target = ["spotFactory.SpotMarketProxy"]
fromCall.func = "getMarketOwner"
fromCall.args = ["<%= extras.fx_susde_market_id %>"]
func = "setSettlementStrategy"
args = [
    "<%= extras.fx_susde_market_id %>",
    "<%= extras.fx_susde_settlement_strategy_id %>",
    { strategyType = "1", settlementDelay = "<%= settings.big_cap_settlement_delay %>", settlementWindowDuration = "<%= settings.big_cap_settlement_window_duration %>", priceVerificationContract = "<%= imports.pyth_erc7412_wrapper.contracts.PythERC7412Wrapper.address %>", feedId = "<%= settings.pyth_feed_id_susde %>", url = "<%= settings.pyth_feed_url_susde %>", settlementReward = "<%= settings.settlement_reward %>", minimumUsdExchangeAmount = "<%= settings.settlement_minimum_usd_exchange_amount %>", maxRoundingLoss = "<%= settings.settlement_max_rounding_loss %>", priceDeviationTolerance = "<%= settings.price_deviation_tolerance %>", disabled = true },
]

[invoke.SpotMarketProxy_setAtomicFixedFee_fxSUSDe]
target = ["spotFactory.SpotMarketProxy"]
fromCall.func = "getMarketOwner"
fromCall.args = ["<%= extras.fx_susde_market_id %>"]
func = "setAtomicFixedFee"
args = ["<%= extras.fx_susde_market_id %>", "<%= parseEther(String(0.02)) %>"]

[invoke.configure_fxsusde_collateral]
target = ["system.CoreProxy"]
fromCall.func = "owner"
func = "configureCollateral"  # "args" see below in the multiline block

[[invoke.configure_fxsusde_collateral.args]]
tokenAddress = "<%= extras.fx_susde_token_address %>"
oracleNodeId = "<%= extras.SUSDE_staleness_oracle_id %>"
issuanceRatioD18 = "<%= MaxUint256 %>"
liquidationRatioD18 = "<%= parseEther('1.2') %>"
liquidationRewardD18 = "<%= parseEther('1') %>"
minDelegationD18 = "<%= parseEther('100') %>"
depositingEnabled = true

