[invoke.registerperpsPltrPythOracleNode]
target = [
    "system.oracle_manager.Proxy",
]
func = "registerNode"
args = [
    5,
    "<%= defaultAbiCoder.encode(['address', 'bytes32', 'bool'], [settings.pyth_price_verification_address, settings.pythPltrFeedId, false]) %>",
    [],
]
depends = [
    "provision.system",
]

[invoke.registerperpsPltrPythOracleNode.extra.perpsPltr_pyth_oracle_id]
event = "NodeRegistered"
arg = 0

[invoke.registerperpsPltrLookupOracleNode]
target = [
    "system.oracle_manager.Proxy",
]
func = "registerNode"
args = [
    9,
    "<%= defaultAbiCoder.encode(['address', 'bytes32', 'uint256'], [imports.pyth_erc7412_wrapper.contracts.PythERC7412Wrapper.address, settings.pythPltrFeedId, settings.bigCapDefaultStalenessTolerance]) %>",
    [],
]
depends = [
    "provision.system",
]

[invoke.registerperpsPltrLookupOracleNode.extra.perpsPltr_lookup_oracle_id]
event = "NodeRegistered"
arg = 0

[invoke.registerperpsPltrOracleNode]
target = [
    "system.oracle_manager.Proxy",
]
func = "registerNode"
args = [
    7,
    "<%= defaultAbiCoder.encode(['uint256'], [settings.bigCapDefaultStalenessTolerance]) %>",
    [
        "<%= extras.perpsPltr_pyth_oracle_id %>",
        "<%= extras.perpsPltr_lookup_oracle_id %>",
    ],
]
depends = [
    "provision.system",
]

[invoke.registerperpsPltrOracleNode.extra.pltr_oracle_id]
event = "NodeRegistered"
arg = 0
