[invoke.registerperpsTslaPythOracleNode]
target = [
    "system.oracle_manager.Proxy",
]
func = "registerNode"
args = [
    5,
    "<%= defaultAbiCoder.encode(['address', 'bytes32', 'bool'], [settings.pyth_price_verification_address, settings.pythTslaFeedId, false]) %>",
    [],
]
depends = [
    "provision.system",
]

[invoke.registerperpsTslaPythOracleNode.extra.perpsTsla_pyth_oracle_id]
event = "NodeRegistered"
arg = 0

[invoke.registerperpsTslaLookupOracleNode]
target = [
    "system.oracle_manager.Proxy",
]
func = "registerNode"
args = [
    9,
    "<%= defaultAbiCoder.encode(['address', 'bytes32', 'uint256'], [imports.pyth_erc7412_wrapper.contracts.PythERC7412Wrapper.address, settings.pythTslaFeedId, settings.bigCapDefaultStalenessTolerance]) %>",
    [],
]
depends = [
    "provision.system",
]

[invoke.registerperpsTslaLookupOracleNode.extra.perpsTsla_lookup_oracle_id]
event = "NodeRegistered"
arg = 0

[invoke.registerperpsTslaOracleNode]
target = [
    "system.oracle_manager.Proxy",
]
func = "registerNode"
args = [
    7,
    "<%= defaultAbiCoder.encode(['uint256'], [settings.bigCapDefaultStalenessTolerance]) %>",
    [
        "<%= extras.perpsTsla_pyth_oracle_id %>",
        "<%= extras.perpsTsla_lookup_oracle_id %>",
    ],
]
depends = [
    "provision.system",
]

[invoke.registerperpsTslaOracleNode.extra.tsla_oracle_id]
event = "NodeRegistered"
arg = 0
