[invoke.registerperpsHoodPythOracleNode]
target = [
    "system.oracle_manager.Proxy",
]
func = "registerNode"
args = [
    5,
    "<%= defaultAbiCoder.encode(['address', 'bytes32', 'bool'], [settings.pyth_price_verification_address, settings.pythHoodFeedId, false]) %>",
    [],
]
depends = [
    "provision.system",
]

[invoke.registerperpsHoodPythOracleNode.extra.perpsHood_pyth_oracle_id]
event = "NodeRegistered"
arg = 0

[invoke.registerperpsHoodLookupOracleNode]
target = [
    "system.oracle_manager.Proxy",
]
func = "registerNode"
args = [
    9,
    "<%= defaultAbiCoder.encode(['address', 'bytes32', 'uint256'], [imports.pyth_erc7412_wrapper.contracts.PythERC7412Wrapper.address, settings.pythHoodFeedId, settings.bigCapDefaultStalenessTolerance]) %>",
    [],
]
depends = [
    "provision.system",
]

[invoke.registerperpsHoodLookupOracleNode.extra.perpsHood_lookup_oracle_id]
event = "NodeRegistered"
arg = 0

[invoke.registerperpsHoodOracleNode]
target = [
    "system.oracle_manager.Proxy",
]
func = "registerNode"
args = [
    7,
    "<%= defaultAbiCoder.encode(['uint256'], [settings.bigCapDefaultStalenessTolerance]) %>",
    [
        "<%= extras.perpsHood_pyth_oracle_id %>",
        "<%= extras.perpsHood_lookup_oracle_id %>",
    ],
]
depends = [
    "provision.system",
]

[invoke.registerperpsHoodOracleNode.extra.hood_oracle_id]
event = "NodeRegistered"
arg = 0
