[invoke.registerperpsCoinPythOracleNode]
target = [
    "system.oracle_manager.Proxy",
]
func = "registerNode"
args = [
    5,
    "<%= defaultAbiCoder.encode(['address', 'bytes32', 'bool'], [settings.pyth_price_verification_address, settings.pythCoinFeedId, false]) %>",
    [],
]
depends = [
    "provision.system",
]

[invoke.registerperpsCoinPythOracleNode.extra.perpsCoin_pyth_oracle_id]
event = "NodeRegistered"
arg = 0

[invoke.registerperpsCoinLookupOracleNode]
target = [
    "system.oracle_manager.Proxy",
]
func = "registerNode"
args = [
    9,
    "<%= defaultAbiCoder.encode(['address', 'bytes32', 'uint256'], [imports.pyth_erc7412_wrapper.contracts.PythERC7412Wrapper.address, settings.pythCoinFeedId, settings.bigCapDefaultStalenessTolerance]) %>",
    [],
]
depends = [
    "provision.system",
]

[invoke.registerperpsCoinLookupOracleNode.extra.perpsCoin_lookup_oracle_id]
event = "NodeRegistered"
arg = 0

[invoke.registerperpsCoinOracleNode]
target = [
    "system.oracle_manager.Proxy",
]
func = "registerNode"
args = [
    7,
    "<%= defaultAbiCoder.encode(['uint256'], [settings.bigCapDefaultStalenessTolerance]) %>",
    [
        "<%= extras.perpsCoin_pyth_oracle_id %>",
        "<%= extras.perpsCoin_lookup_oracle_id %>",
    ],
]
depends = [
    "provision.system",
]

[invoke.registerperpsCoinOracleNode.extra.coin_oracle_id]
event = "NodeRegistered"
arg = 0
